language: swift
xcode_project: ViewElements.xcodeproj
matrix:
  include:
    xcode_scheme: ViewElements
osx_image: xcode9.3

branches:
  only:
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.3.0
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update

machine:
  xcode:
    version: "9.3"

deployment:
  release:
    tag: /.*/
    commands:
      - pod trunk push


script:
  - xcodebuild -destination 'platform=iOS Simulator,name=iPhone 5s,OS=11.3' -project ViewElements.xcodeproj -scheme ViewElements test
