language: swift
xcode_project: ViewElements.xcodeproj
matrix:
  include:
    xcode_scheme: ViewElements
osx_image: xcode9.3

branches:
  only:
    - master
    - release

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.3.0
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update

machine:
  xcode:
    version: "9.3"

deploy:
  provider: script
  script: sh scripts/push.sh
  on:
    tag: true
    branch: release

script:
  - set -o pipefail
  - xcodebuild -destination 'platform=iOS Simulator,name=iPhone 5s,OS=11.3' -project ViewElements.xcodeproj -scheme ViewElements test | xcpretty

notifications:
  email:
    recipients:
      - aun.wirawit@gmail.com
    on_success: never
    on_failure: always